### ISSUE TITLE
OpenG Error Library

### ISSUE THREAD

**Issue by felipefoz** [vipm-io/OpenG-Variant-Data-Library#5]
Hi Jim and everyone,

I've been doing some experiments on using source code directly from github on my projects and this library might be useful in my projects. I noticed that this library depends on openg error library, is this listed anywhere in Github?

Regards,

**Comment by jimkring** [comment]
Easiest place to look is the [lvdata.dragon](https://github.com/vipm-io/OpenG-Variant-Data-Library/blob/master/lvdata.dragon) file. FYI, see [dragon.vipm.io](https://dragon.vipm.io)

That info can be found if you look in the [.vipc](https://github.com/vipm-io/OpenG-Variant-Data-Library/blob/master/source/.vipc) and [.vipb](https://github.com/vipm-io/OpenG-Variant-Data-Library/blob/master/source/.vipb)
