### ISSUE TITLE
Missing case for FIXED-POINT 

### ISSUE THREAD

**Issue by fbalzarotti** [vipm-io/OpenG-Variant-Data-Library#6]
Hi, 

The function _OpenG.lib\lvdata\lvdata.llb\Get Data Name from TD__ogtk.vi is currently not handling "Fixed Point" data type.

A simple fix is to add "Fixed Point" to the case that handles "DAQ" and "Refunm". 

I'd appreciate it if you recompile it with this change!

Best, 
Francisco

**Comment by fbalzarotti** [comment]
Same thing applies to _OpenG.lib\lvdata\lvdata.llb\Set Data Name__ogtk.vi

Handling a "Fixed Point" can be done assigning the same case as for "Refnum"

**Comment by jimkring** [comment]
Hi @fbalzarotti. Yes, that seams reasonable. Which version of LabVIEW are you using, by the way?

**Comment by RaphSchru** [comment]
Hi, I just stumbled upon the exact same issue with "Set Data Name__ogtk.vi" not supporting fixed-point type.
I am using LV 2020.

**Comment by RaphSchru** [comment]
Hi again, the case is also missing for "Get Default Data from TD__ogtk.vi".

**Comment by jimkring** [comment]
Hi @RaphSchru and @fbalzarotti. I was curious what version of LabVIEW you are both using?

**Comment by RaphSchru** [comment]
LV2019 and LV2020

**Comment by jimkring** [comment]
Will be fixed in next release (6.0).

![image](https://github.com/vipm-io/OpenG-Variant-Data-Library/assets/381432/fcf7017b-6c59-483c-826f-5fc46b58b75b)

![image](https://github.com/vipm-io/OpenG-Variant-Data-Library/assets/381432/750d5ecf-fd42-42d1-8098-1c2400e90893)

**Comment by jimkring** [comment]
@all-contributors add @fbalzarotti for bug

**Comment by jimkring** [comment]
@all-contributors add @RaphSchru for bug
