### ISSUE TITLE
Openg-Get-Cluster-Element-Names-ogtk-vi

### ISSUE THREAD

**Issue by 158545614** [vipm-io/OpenG-Variant-Data-Library#7]
https://forums.ni.com/t5/LabVIEW/Openg-Get-Cluster-Element-Names-ogtk-vi/m-p/4330780/highlight/false#M1268921

**Comment by RaphSchru** [comment]
To detail a bit more the issue, I think this is actually a request to support Maps and Sets in the OpenG Variant Data Library.
Regards, Raphaël.

**Comment by jimkring** [comment]
We're looking into maps and sets support. Please follow #20. (I'm going to close this issue #7)
